version: '3.8'
volumes:
  db_data:
  # web_data:
  static_data:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  #rabbit:
  #  restart: always
  #  image: rabbitmq
  #  ports:
  #    - "5672:5672"
  #  depends_on:
  #    - db

  web:
    build: ./script_db
    # container_name: 'app'
    restart: always
    command: gunicorn script_db.wsgi:application --bind 0:8000
    # python manage.py collectstatic"
    #command: python manage.py runserver 0.0.0.0:8000
    volumes:
    #   - web_data:/app
      - static_data:/app/static/
    #depends_on:
    #  - rabbit
    env_file:
      - ./.env
    #ports:
    #  - '8000:8000'

  #celery:
  #  build: ./script_db
  #  container_name: 'app_celery'
  #  command: celery -A script_db worker --loglevel=info --pool=solo
  #  volumes:
  #    - .:/app
  #  links:
  #    - rabbit
  #  depends_on:
  #    - web
  #    - rabbit

  # frontend:
  #   build:
  #     context: ./react-interface
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./react-interface/:/app/result_build/
  #   depends_on:
  #     - web

  nginx:
    image: nginx:1.21.3-alpine
    container_name: 'nginx'
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/html/static/
    #   - ./react-interface/build:/usr/share/nginx/html/
    depends_on:
      - web
    #  - celery