version: '3.8'
volumes:
  db_data:
  static_d:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  rabbit:
    restart: always
    image: rabbitmq
    hostname: rabbit
    environment:
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"

  web:
    build: ./script_db
    restart: always
    command: bash -c "
      gunicorn script_db.wsgi:application --bind 0:8000 &
      celery -A script_db worker --loglevel=info --pool=solo -B"
    volumes:
      - static_d:/app/static/
    depends_on:
      - db
    links:
      - rabbit
    env_file:
      - ./.env
  
  nginx:
    image: nginx:1.21.3-alpine
    container_name: 'nginx'
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_d:/var/html/static/
    depends_on:
      - web
