version: '3.8'
volumes:
  static_data:
  db_data:


services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    build: ./script_db
    restart: always
    volumes:
      - static_data:/app/static/
    depends_on:
      - db
    env_file:
      - ./.env

  # frontend:
  #   build:
  #     context: ./react-interface
  #     dockerfile: Dockerfile
  #   volumes:
  #     - ./react-interface/:/app/result_build/
  #   depends_on:
  #     - web

  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - static_data:/var/html/static/
  #     - ./react-interface/build:/usr/share/nginx/html/
    depends_on:
      - web
