# Generated by Django 3.0 on 2022-06-23 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(help_text='№', verbose_name='№')),
                ('order_num', models.IntegerField(help_text='заказ №', verbose_name='заказ №')),
                ('cost', models.IntegerField(help_text='долл. США', verbose_name='стоимость,$')),
                ('delivery_date', models.DateField(help_text='срок поставки', verbose_name='срок поставки')),
                ('cost_rub', models.DecimalField(decimal_places=1, help_text='стоимость,руб.', max_digits=6, verbose_name='стоимость,руб.')),
            ],
            options={
                'verbose_name': 'Запись таблицы заказов',
                'verbose_name_plural': 'Записи таблицы заказов',
            },
        ),
    ]
