# Generated by Django 3.0 on 2022-06-23 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_collect', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='record',
            options={'ordering': ['id'], 'verbose_name': 'Запись таблицы заказов', 'verbose_name_plural': 'Записи таблицы заказов'},
        ),
    ]
